name: breed-classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - tqdm
  - pyyaml
  - jupyter
  - ipykernel
  - albumentations
  - onnx
  - onnxruntime
  - streamlit
  - pip:
      - timm
