name: breed-classifier
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - tqdm
  - pyyaml
  - jupyter
  - ipykernel
  - albumentations
  - onnx
  - onnxruntime
  - streamlit
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - timm
      - ultralytics
